replicaCount: 1

image:
  repository: "devuser103/podinfo"
  tag: "0.1.0"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80
  targetPort: 8080

env:
  APP_ENV: "dev"
  THEME_COLOR: "blue"
  APP_VERSION: "unknown"
  GIT_SHA: "unknown"

resources: {}

nodeSelector:
  workload/node-group: podinfo-app
