apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "podinfo.fullname" . }}
  labels:
    {{- include "podinfo.labels" . | nindent 4 }}
data:
  APP_ENV: {{ .Values.env.APP_ENV | quote }}
  THEME_COLOR: {{ .Values.env.THEME_COLOR | quote }}
  APP_VERSION: {{ .Values.env.APP_VERSION | quote }}
  GIT_SHA: {{ .Values.env.GIT_SHA | quote }}
